import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, Clock, CheckCircle, Activity, Brain, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export default function IncidentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_URL}/api/incidents/${id}`)
      .then(res => res.json())
      .then(data => {
        setData(data);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to fetch incident:", err);
        setLoading(false);
      });
  }, [id]);

  if (loading) return <div className="p-8 text-center text-gray-500">Loading incident details...</div>;
  if (!data) return <div className="p-8 text-center text-red-500">Incident not found.</div>;

  const getRiskColor = (score) => {
    if (score >= 80) return 'text-red-600 bg-red-100 border-red-200';
    if (score >= 60) return 'text-orange-600 bg-orange-100 border-orange-200';
    return 'text-yellow-600 bg-yellow-100 border-yellow-200';
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(220, 38, 38);
    doc.text('Incident Report', 20, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Incident ID: ${data.incident_id}`, 20, 35);
    doc.text(`Title: ${data.title}`, 20, 45);
    doc.text(`Risk Score: ${data.risk_score}/100`, 20, 55);
    doc.text(`Severity: ${data.severity}`, 20, 65);
    
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Root Cause Analysis', 20, 85);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(data.root_cause || 'Not identified', 20, 95);
    
    let yPos = 110;
    if (data.ai_explanation) {
      doc.setFontSize(14);
      doc.setTextColor(37, 99, 235);
      doc.text('AI Explanation', 20, yPos);
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      const splitExplanation = doc.splitTextToSize(data.ai_explanation, 170);
      doc.text(splitExplanation, 20, yPos + 10);
      yPos += 10 + (splitExplanation.length * 5) + 10;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Recommended Actions', 20, yPos);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    data.recommendations.forEach((rec, index) => {
      doc.text(`${index + 1}. ${rec}`, 25, yPos + 10 + (index * 7));
    });
    
    yPos += 10 + (data.recommendations.length * 7) + 15;
    if (yPos > 230) { doc.addPage(); yPos = 20; }

    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Event Timeline', 20, yPos);
    
    const timelineData = data.timeline.map(event => [event.time, event.system, event.description]);
    
    autoTable(doc, {
      startY: yPos + 5,
      head: [['Time', 'System', 'Event']],
      body: timelineData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] }
    });
    
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by Enterprise Digital Shadow | Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10);
    }
    doc.save(`incident-report-${data.incident_id}.pdf`);
  };

  return (
    <div className="p-8 bg-gray-50 min-h-screen font-sans">
      <button onClick={() => navigate('/')} className="flex items-center text-gray-600 hover:text-blue-600 mb-6">
        <ArrowLeft size={20} className="mr-2" /> Back to Dashboard
      </button>

      <div className="bg-white rounded-lg shadow-sm p-6 mb-6 border-l-4 border-red-500">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold text-gray-800 flex items-center">
              <AlertTriangle className="text-red-500 mr-2" size={24} />
              {data.title}
            </h1>
            <p className="text-gray-500 mt-1">Incident ID: <span className="font-mono">{data.incident_id}</span></p>
          </div>
          <div className="flex gap-3">
            <button onClick={exportToPDF} className="flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">
              <Download size={16} className="mr-2" /> Export PDF
            </button>
            <div className={`px-4 py-2 rounded-lg border text-xl font-bold ${getRiskColor(data.risk_score)}`}>
              Risk: {data.risk_score}/100
            </div>
          </div>
        </div>
      </div>

      {data.ai_explanation && (
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg shadow-sm p-6 mb-6 border-l-4 border-blue-500">
          <h2 className="text-lg font-semibold mb-3 flex items-center text-gray-800">
            <Brain className="text-blue-500 mr-2" size={20} /> AI-Powered Explanation
          </h2>
          <p className="text-gray-700 leading-relaxed text-base">{data.ai_explanation}</p>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white rounded-lg shadow-sm p-6">
          <h2 className="text-lg font-semibold mb-4 flex items-center text-gray-800">
            <Activity className="text-blue-500 mr-2" size={20} /> Analysis
          </h2>
          <div className="space-y-4">
            <div>
              <p className="text-sm text-gray-500 font-medium">Possible Root Cause</p>
              <p className="text-gray-800 font-medium mt-1">{data.root_cause}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 font-medium">Affected Systems</p>
              <div className="flex flex-wrap gap-2 mt-2">
                {data.affected_systems.map(sys => (
                  <span key={sys} className="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm font-medium">{sys}</span>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-sm p-6">
          <h2 className="text-lg font-semibold mb-4 flex items-center text-gray-800">
            <CheckCircle className="text-green-500 mr-2" size={20} /> Recommended Actions
          </h2>
          <ul className="space-y-3">
            {data.recommendations.map((rec, index) => (
              <li key={index} className="flex items-start">
                <span className="flex-shrink-0 w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm font-bold mr-3 mt-0.5">{index + 1}</span>
                <span className="text-gray-700">{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-sm p-6 mt-6">
        <h2 className="text-lg font-semibold mb-4 flex items-center text-gray-800">
          <Clock className="text-purple-500 mr-2" size={20} /> Event Timeline
        </h2>
        <div className="space-y-4">
          {data.timeline.map((event, index) => (
            <div key={index} className="flex items-start">
              <div className="flex flex-col items-center mr-4">
                <div className="w-3 h-3 bg-purple-500 rounded-full"></div>
                {index !== data.timeline.length - 1 && <div className="w-0.5 h-full bg-gray-200 mt-1"></div>}
              </div>
              <div className="pb-4">
                <p className="text-sm font-mono text-gray-500">{event.time}</p>
                <p className="text-gray-800 font-medium">{event.description}</p>
                <p className="text-sm text-gray-500">System: {event.system}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}