import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, Clock, CheckCircle, Activity, Brain, Download, TrendingUp, Zap } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export default function IncidentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_URL}/api/incidents/${id}`)
      .then(res => res.json())
      .then(data => {
        setData(data);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to fetch incident:", err);
        setLoading(false);
      });
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="glass rounded-2xl p-8 text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-white mx-auto mb-4"></div>
          <p className="text-white text-lg">Loading incident details...</p>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="glass rounded-2xl p-8 text-center">
          <AlertTriangle className="text-red-400 mx-auto mb-4" size={64} />
          <p className="text-white text-xl">Incident not found</p>
        </div>
      </div>
    );
  }

  const getRiskGradient = (score) => {
    if (score >= 80) return 'from-red-500 to-pink-500';
    if (score >= 60) return 'from-orange-500 to-red-500';
    return 'from-yellow-500 to-orange-500';
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(220, 38, 38);
    doc.text('Incident Report', 20, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Incident ID: ${data.incident_id}`, 20, 35);
    doc.text(`Title: ${data.title}`, 20, 45);
    doc.text(`Risk Score: ${data.risk_score}/100`, 20, 55);
    doc.text(`Severity: ${data.severity}`, 20, 65);
    
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Root Cause Analysis', 20, 85);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(data.root_cause || 'Not identified', 20, 95);
    
    let yPos = 110;
    if (data.ai_explanation) {
      doc.setFontSize(14);
      doc.setTextColor(37, 99, 235);
      doc.text('AI Explanation', 20, yPos);
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      const splitExplanation = doc.splitTextToSize(data.ai_explanation, 170);
      doc.text(splitExplanation, 20, yPos + 10);
      yPos += 10 + (splitExplanation.length * 5) + 10;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Recommended Actions', 20, yPos);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    data.recommendations.forEach((rec, index) => {
      doc.text(`${index + 1}. ${rec}`, 25, yPos + 10 + (index * 7));
    });
    
    yPos += 10 + (data.recommendations.length * 7) + 15;
    if (yPos > 230) { doc.addPage(); yPos = 20; }

    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('Event Timeline', 20, yPos);
    
    const timelineData = data.timeline.map(event => [event.time, event.system, event.description]);
    
    autoTable(doc, {
      startY: yPos + 5,
      head: [['Time', 'System', 'Event']],
      body: timelineData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] }
    });
    
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by Enterprise Digital Shadow | Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10);
    }
    doc.save(`incident-report-${data.incident_id}.pdf`);
  };

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-7xl mx-auto">
        {/* Back Button */}
        <button 
          onClick={() => navigate('/')} 
          className="glass text-white px-6 py-3 rounded-xl hover:bg-white/20 transition-all flex items-center gap-2 mb-6 animate-fade-in"
        >
          <ArrowLeft size={20} /> Back to Dashboard
        </button>

        {/* Incident Header */}
        <div className="glass rounded-2xl p-8 mb-6 animate-fade-in pulse-glow">
          <div className="flex justify-between items-start">
            <div className="flex-1">
              <div className="flex items-center gap-4 mb-4">
                <div className="bg-red-500/20 p-4 rounded-2xl">
                  <AlertTriangle className="text-red-400" size={40} />
                </div>
                <div>
                  <h1 className="text-4xl font-bold text-white mb-2">{data.title}</h1>
                  <p className="text-white/60 text-lg font-mono">ID: {data.incident_id}</p>
                </div>
              </div>
            </div>
            <div className="flex flex-col gap-4 items-end">
              <button 
                onClick={exportToPDF} 
                className="btn-success text-white px-6 py-3 rounded-xl flex items-center gap-2 font-medium"
              >
                <Download size={20} /> Export PDF
              </button>
              <div className={`bg-gradient-to-r ${getRiskGradient(data.risk_score)} px-8 py-4 rounded-2xl text-center`}>
                <p className="text-white/80 text-sm font-medium mb-1">Risk Score</p>
                <p className="text-5xl font-bold text-white">{data.risk_score}</p>
              </div>
            </div>
          </div>
        </div>

        {/* AI Explanation */}
        {data.ai_explanation && (
          <div className="glass rounded-2xl p-8 mb-6 animate-fade-in border-l-4 border-blue-500">
            <h2 className="text-2xl font-bold text-white mb-4 flex items-center">
              <Brain className="text-blue-400 mr-3" size={28} />
              AI-Powered Analysis
            </h2>
            <p className="text-white/80 leading-relaxed text-lg">{data.ai_explanation}</p>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          {/* Root Cause */}
          <div className="glass rounded-2xl p-8 animate-slide-in">
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
              <Activity className="text-purple-400 mr-3" size={28} />
              Root Cause Analysis
            </h2>
            <div className="bg-white/5 rounded-xl p-6 mb-6">
              <p className="text-white/60 text-sm font-medium mb-2">Probable Cause</p>
              <p className="text-white text-lg font-medium">{data.root_cause}</p>
            </div>
            <div>
              <p className="text-white/60 text-sm font-medium mb-3">Affected Systems</p>
              <div className="flex flex-wrap gap-2">
                {data.affected_systems.map(sys => (
                  <span key={sys} className="bg-white/10 text-white px-4 py-2 rounded-xl text-sm font-medium border border-white/20">
                    {sys}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Recommendations */}
          <div className="glass rounded-2xl p-8 animate-slide-in">
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
              <CheckCircle className="text-green-400 mr-3" size={28} />
              Recommended Actions
            </h2>
            <div className="space-y-4">
              {data.recommendations.map((rec, index) => (
                <div key={index} className="flex items-start gap-4 bg-white/5 rounded-xl p-4">
                  <div className="bg-gradient-to-br from-blue-500 to-purple-500 w-10 h-10 rounded-xl flex items-center justify-center text-white font-bold flex-shrink-0">
                    {index + 1}
                  </div>
                  <p className="text-white/80 text-base pt-2">{rec}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Timeline */}
        <div className="glass rounded-2xl p-8 animate-fade-in">
          <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
            <Clock className="text-cyan-400 mr-3" size={28} />
            Event Timeline
          </h2>
          <div className="space-y-4">
            {data.timeline.map((event, index) => (
              <div key={index} className="flex items-start gap-6 animate-slide-in" style={{ animationDelay: `${index * 0.1}s` }}>
                <div className="flex flex-col items-center">
                  <div className="bg-gradient-to-br from-cyan-500 to-blue-500 w-4 h-4 rounded-full pulse-glow"></div>
                  {index !== data.timeline.length - 1 && (
                    <div className="w-0.5 h-16 bg-gradient-to-b from-cyan-500/50 to-transparent mt-2"></div>
                  )}
                </div>
                <div className="flex-1 bg-white/5 rounded-xl p-6 hover:bg-white/10 transition-colors">
                  <div className="flex items-center gap-4 mb-2">
                    <span className="font-mono text-cyan-400 text-sm">{event.time}</span>
                    <span className="bg-white/10 text-white px-3 py-1 rounded-lg text-xs font-medium">
                      {event.system}
                    </span>
                  </div>
                  <p className="text-white text-lg font-medium">{event.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}